name: Check PR

on:
  pull_request:
    branches: [ staging, prod ]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - uses: actions/setup-node@v2
        with:
          node-version: '15'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check prettier
        run: npm run prettier:check

      - name: Check eslint
        run: npm run lint:check

      - name: Typescript check
        run: npm run ts:check

      - uses: naveenk1223/action-pr-title@master
        with:
          regex: '^(feat|fix|perf|refactor|revert|test|test|build|chore)([(a-z-)]*):\s[a-z0-9\s,()]+$' # Regex the title should match.
          prefix_case_sensitive: true
          min_length: 10
          max_length: 80
