name: Sonarqube

on:
  push:
    branches: [ staging ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcube:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-sonarcube
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
