name: Sonarqube
on:
  push:
    branches: [ staging ]

jobs:
  sonarcube:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}-sonarcube
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
